import { ROLES } from "../roles";
import { PERMISSIONS } from "../permissions";

export const CAPABILITIES = {
  [ROLES.USER]: [],
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_ADMIN,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_FILES,
    PERMISSIONS.MANAGE_TESTS,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.VIEW_ANALYTICS
  ],
  [ROLES.SUPERADMIN]: [
    PERMISSIONS.VIEW_ADMIN,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_FILES,
    PERMISSIONS.MANAGE_TESTS,
    PERMISSIONS.VIEW_PAYMENTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.SYSTEM_CONTROL
  ]
};
